### PR TITLE
ir: Whitelist items that don't generate code to improve derive behavior.

### LINKED ISSUE #1454: Copy not derived when using whitelist_recursively(false)
### Input C/C++ Header

```C++
#include <stdint.h>
#include <stdlib.h>
typedef uint64_t mbedtls_mpi_uint;
typedef struct
{
    int s;              /*!<  integer sign      */
    size_t n;           /*!<  total # of limbs  */
    mbedtls_mpi_uint *p;          /*!<  pointer to limbs  */
}
mbedtls_mpi;
```

### Bindgen Invocation

```Rust
    let bindings = bindgen::builder()
        .header_contents("test.h", ...)
        .trust_clang_mangling(false)
        .derive_copy(true)
        .whitelist_type("mbedtls_.*")
        .whitelist_recursively(whitelist_recursively)
        .layout_tests(false)
        .generate()
        .expect("bindgen error");
```

### Actual Results

```rust
// whitelist_recursively = false
/* automatically generated by rust-bindgen */

pub type mbedtls_mpi_uint = u64;
#[repr(C)]
pub struct mbedtls_mpi {
    ///<  integer sign
    pub s: ::std::os::raw::c_int,
    ///<  total # of limbs
    pub n: usize,
    ///<  pointer to limbs
    pub p: *mut mbedtls_mpi_uint,
}
```

### Expected Results

```Rust
// whitelist_recursively = true
/* automatically generated by rust-bindgen */

pub type mbedtls_mpi_uint = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_mpi {
    ///<  integer sign
    pub s: ::std::os::raw::c_int,
    ///<  total # of limbs
    pub n: usize,
    ///<  pointer to limbs
    pub p: *mut mbedtls_mpi_uint,
}
```

### PR DESCRIPTION
**Pull request by emilio**
When not whitelisting recursively.

Fixes #1454

### CODE REVIEW

**Comment by jethrogb** [comment]
I don't think this is going to work in the generic case. For example, what if you're using types from another crate like `libc::rlimit`.

**Comment by emilio** [comment]
Can you put an example? You mean blacklisting `rlimit` and using `core::libc::rlimit` for example? I think we should be able to make that work.

**Comment by jethrogb** [comment]
After working on #1540, I actually think this *should* be merged, even though it's not a fix for #1454.

**Comment by jethrogb** [comment]
ping

**Comment by emilio** [comment]
Yeah, need to get to rebase this, sorry. I try contributions not to linger a lot, but I usually deprioritize my own work. Will try to do this tonight :)

**Comment by jethrogb** [comment]
Test `tests/headers/no-recursive-whitelisting.h` no longer tests the right thing.

**Pull request merged**
