### PR TITLE
issue 1723

### PR DESCRIPTION
**Pull request by smurfd**
Hey

This might be a start to fix this issue. Bare with me :)

I created a `Bindings::generate_common()` that i call from `Bindings::generate()`but im unsure if i used the right "parts" of `generate()` and possibly where we should call the `Bindings::generate_common()` to avoid BINDGEN_EXTRA_CLANG_ARGS being evaluated after `dump-preprocessed-input()`

### CODE REVIEW

**Comment by emilio** [comment]
Yeah, so this is a good start, but not quite what I meant (it might be that I goofed a bit on the description).

The main thing we have to do is making sure that the option shenanigans we do in `Builder::generate`:

https://github.com/rust-lang/rust-bindgen/blob/a467d3efc6f9fbe2e811468adbaa3687a9938b0d/src/lib.rs#L1307-L1333

get applied to `dump_preprocessed_input`. It may be easy enough to move those to a separate function, clone the current options in `dump_preprocessed_input`, and call that function.

Does that make sense?

**Comment by smurfd** [comment]
Hey. yeah that makes sense i think. ill remove the `generate_common()` then I do something like :
```
fn generate_options(self, mut opt: BindgenOptions) -> BindgenOptions { ....}
``` 
with this in it 
https://github.com/rust-lang/rust-bindgen/blob/a467d3efc6f9fbe2e811468adbaa3687a9938b0d/src/lib.rs#L1307-L1333

generate looks:
```
    pub fn generate(mut self) -> Result<Bindings, ()> {
        Bindings::generate(self.generate_options(generate.options))
    }
```
call that from 
https://github.com/rust-lang/rust-bindgen/blob/a467d3efc6f9fbe2e811468adbaa3687a9938b0d/src/lib.rs#L1404
Where i pass the `self.options` as a parameter.

.... ofcourse i run into the whole : `move occurs because value has type BindgenOptions, which does not implement the Copy trait`
And im pretty sure you don't want the Copy,Clone traits implemented :)

Is it something similarly done else where that i can look at?

**Comment by smurfd** [comment]
Its easier to see what i was talking about if i show you... hence ^

**Comment by smurfd** [comment]
nooooooooooooooo i did something wrong :'(

**Comment by emilio** [comment]
I think what I'd do is: 

```
git fetch upstream
git rebase upstream/master
# Hit conflicts? git mergetool, and solve them, then git rebase --continue
git push -f
```

**Comment by emilio** [comment]
Or alternatively:

```
git diff upstream/master > diff
git reset --hard upstream/master
git apply diff
git commit -am "Issue 1723"
git push -f
```

That should leave you with your changes, but just one commit on top of master.

**Comment by smurfd** [comment]
THANK YOU! phew , we are back to 1 commit again. :)
used the 2nd alternative. but got a problem when i pushed.
```
$ git push -f 
fatal: The current branch issue-1723 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin issue-1723
```
got some other problem when i ran that command. But after some searching i found this 
`$ git config --global push.default current`

after that i was able to push :)

**Comment by smurfd** [comment]
same thing again :( ill fix

**Comment by smurfd** [comment]
for info, this latest patch might actually be what we are looking for.
It builds and passes the `cargo test` tests

**Comment by smurfd** [comment]
forgot to remove the `generate_common()` i had in my 1st patch.

**Comment by emilio** [comment]
I took the liberty of updating this. It needed a few changes because making `dump_preprocessed_input` take `&mut` would be a breaking change. But it ended up being simple enough.

Thanks a lot @smurfd, and sorry I ended up missing your previous update for so long.

**Pull request merged**
