### PR TITLE
Replace the `TraversalPredicate` trait with an alias type

### PR DESCRIPTION
**Pull request by pvdrz**
Fixes https://github.com/rust-lang/rust-bindgen/issues/2261

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Nice clean-up!

**Comment by pvdrz** [comment]
r=emilio

(my bors-fu sucks so I hope this works :sweat_smile:)

**Comment by pvdrz** [comment]
@bors-servo r+

(my bors-fu sucks so I hope this works :sweat_smile:)

**Comment by emilio** [comment]
Sorry, I didn't merge right away because CI was still running, thanks for the reminder :)

**Pull request merged**
