### PR TITLE
Update which, quote and proc_macro.

### LINKED ISSUE #1407: Update clang-sys, cexpr, which to latest versions
It would be helpful for me as a Fedora packager to be able to use latest versions of mentioned dependncies in latest versions (so I don't have to package old versions).

Would be great also if you release new version of crate ;)

### PR DESCRIPTION
**Pull request by emilio**
Fixes #1407.

### CODE REVIEW

**Comment by emilio** [comment]
cc @Eijebong, last commit is a rebase of yours. If you could take a look it'd be great.

**Comment by ignatenkobrain** [comment]
Meh, it seems that this triggers https://github.com/rust-lang/cargo/issues/2589.

See cbindgen's similar issues: https://github.com/eqrion/cbindgen/issues/203

**Comment by ignatenkobrain** [comment]
it's enough to keep `which` on `1.x` in order to avoid triggering that bug in cargo.

**Comment by emilio** [comment]
> Why don't you need `#[cfg_attr(serde_derive, derive(Serialize)]`?

That's fine for me.

@Eijebong did you manage to take a look at this? Mostly as a sanity check.

**Comment by Eijebong** [comment]
From a quick look it seemed fine. We're running into https://github.com/alexcrichton/proc-macro2/issues/60 a lot though

**Comment by emilio** [comment]
Err, my above comment meant to quote:

> it's enough to keep which on 1.x in order to avoid triggering that bug in cargo.

So @ignatenkobrain I have no preference on landing this as is or with which kept at 1.0. If the latter makes things easier, let me know and I'll remove it from the PR.

**Comment by ignatenkobrain** [comment]
IIUC, if you push this as is, you would have problems with doing cargo install from users because when compiler is updated, binary would be broken.

@cuviper, did i describe problem correctly?

**Comment by cuviper** [comment]
> IIUC, if you push this as is, you would have problems with doing cargo install from users because when compiler is updated, binary would be broken.

This, but also problems if the user tries to run bindgen with a different toolchain active.  e.g. having compiled bindgen with your default-stable rustc, then using it in one of your projects on nightly.  Or vice versa.  Any scenario where the bindgen gets linked to rustc shared libraries will mean your installation is tied to that exact toolchain.

This arises from `which 2.0` -> `failure` -> `failure_derive` -> ... `proc-macro2`, forcing you into linking `libproc_macro` even though `bindgen` wanted it without default features.  `which 1.x` didn't use `failure` at all.

**Comment by cuviper** [comment]
With https://github.com/harryfei/which-rs/pull/9 in `which 2.0.1`, the proc-macro feature will be avoided.

**Comment by Eijebong** [comment]
:party:

**Comment by emilio** [comment]
Ok, so I rebased this, and bumped which as well. Assuming this is green I'll merge. Thanks everyone for all the effort, specially @Eijebong  :)

**Pull request merged**
