### PR TITLE
build: Don't build clap if we're being used as a library.

### PR DESCRIPTION
**Pull request by emilio**
This allows Firefox not to build clap.

### CODE REVIEW

**Comment by emilio** [comment]
(or @pepyakin, or anyone else really)

**Comment by pepyakin** [comment]
So, now instead of `cargo run` one should do `cargo run --features="binaries"`?
Is there a way to leave `cargo run` as it?

**Comment by emilio** [comment]
Hmm... Not that I know of unfortunately.

**Comment by KiChjang** [comment]
`cargo install bindgen` would also be affected. However I think this is ok as long as we make it very clear (in the docs and everywhere) that you need to add the `--features="binaries"` flag.

**Comment by emilio** [comment]
We can also make `binaries` a default feature, but it's unfortunate that it becomes opt-out for library users.

**Comment by SimonSapin** [comment]
Doesn’t `required-features` in the `[[bin]]` section (as already in the PR) fix all this?

**Comment by pepyakin** [comment]
@SimonSapin my first impression was the same :) 

But when I tried `cargo run` it said:

```
error: target `bindgen` requires the features: `binaries`
Consider enabling them by passing e.g. `--features="binaries"`
```

**Comment by SimonSapin** [comment]
That’s just silly… but I suspect that fixing it properly in Cargo requires fixing https://github.com/rust-lang/cargo/issues/4463 first.

**Comment by emilio** [comment]
Closing in favor of https://github.com/rust-lang/rust-bindgen/pull/1581

**Pull request closed without merging**
