### PR TITLE
Turn off regex default features.

### PR DESCRIPTION
**Pull request by PyroLagus**
Fulfills #1622

### CODE REVIEW

**Comment by PyroLagus** [comment]
Should the unicode features (or any others) stay enabled by default?

**Comment by est31** [comment]
@emilio rustfmt should be present again. Could the tests be re-run?

**Comment by emilio** [comment]
This doesn't seem to build:

> error: `std` feature is currently required to build this crate

**Comment by emilio** [comment]
But this looks pretty ok to me otherwise.

**Comment by PyroLagus** [comment]
Odd, it built fine here, but I added std anyways. Maybe I was doing something wrong.

**Pull request merged**
