### PR TITLE
Add ParseCallbacks handler for generated TokenStreams

### PR DESCRIPTION
**Pull request by jandob**
This small feature enables advances users to modify the generated code before it gets converted to a string representation.

### CODE REVIEW

**Comment by jandob** [comment]
My use case is to further process the output. 
I am generating mocks for c functions, and instead of the generated:
```rust
extern "C" {
    pub fn foo();
}
```
i need:
```rust
pub extern "C" fn foo() {
    // generated implementation
}
```
Currently i send the bindgen output to `syn::parse_file`, process the TokenStream and run it through rustfmt. That works, but feels awkward because bindgen already has the TokenStream representation and did rustfmt before.

Essentially, i think the TokenStream is a better representation for what bindgen is actually producing: a syntax tree. 
Converting the tree to source code is the job of another crate: **rustfmt**.

Regarding the dependency on **proc_macro2**: 
A breaking change in proc_macro2 would require a breaking bump. But is this so bad? The bindgen output could also change because of the proc_macro2 update.

**Comment by emilio** [comment]
>  A breaking change in proc_macro2 would require a breaking bump. But is this so bad? The bindgen output could also change because of the proc_macro2 update.

It is not bad as in "common" or such, but it's very easy to forget about... At the very least we need to add a comment in `Cargo.toml` so people don't forget.

Right now bindgen necessarily needs to be updated in order to update proc_macro2 and related crates of course, but if bindgen updates correctly there's no need to change bindgen's output, you just change how you use proc_macro2...

A bit more concerning, I think, is that _any change_ to bindgen's output becomes breaking. Though I guess that is kind of the case already, to some extent...

Anyhow I see the use case, though I'm not quite convinced that exposing the whole syntax tree bindgen generates and proc_macro2's token tree is the right level of abstraction... At the very least, can we just expose one token tree? Right after we call the function, we just call `quote!` to join them together. There's no good reason to provide a vector, as far as I'm concerned, right?

In any case, this is just a bit more convenient way to do this than passing a `String` as a writer to `generate()` and modify that after the fact, right? I'm not sure if the use case is common enough to make it easier than that, but maybe I'm missing something...

**Comment by jandob** [comment]
Ok i changed the PR a bit, now the callback gets invoked in the write method (after TokenStream::to_string() and before rustfmt).

This is how i use it:
```rust
extern crate bindgen;
extern crate syn;
extern crate quote;
use syn;
use quote::ToTokens;

#[derive(Debug)]
struct MyCallbacks;
impl bindgen::callbacks::ParseCallbacks for MyCallbacks {
    fn bindings(&self, bindings: &str) -> Option<String> {
        let mut file = syn::parse_file(&bindings.to_string())
            .expect("Unable to parse bindgen output");
        let mut converter = Converter::new();
        converter.visit_file_mut(&mut file);
        Some(file.into_token_stream().to_string())
    }
}
```

**Comment by emilio** [comment]
My point is, why is this different to passing a string to `generate()`?

**Pull request closed without merging**
