### PR TITLE
Implement #710, must-use for types.

### PR DESCRIPTION
**Pull request by KarelPeeters**
This PR adds an option to generate `#[must_use]` annotations as described in #710.

### CODE REVIEW

**Comment by KarelPeeters** [comment]
That's strange, why is rustfmt suggesting to put the `{` on a new line? The rest of the codebase doesn't do that either.

When I run `cargo fmt` locally it changes pretty much any file so something strange is going on.

**Review by emilio — APPROVED** [review]
Sorry for the lag getting to review this, this looks great. I'll take a look at the rustfmt issue and merge manually if needed. Thanks again!

**Comment by KarelPeeters** [comment]
Awesome, thanks!

I think #710 can be closed now.

**Comment by emilio** [comment]
The reason why rustfmt wanted the brace on its own line was because the condition hits exactly the line length limit, which I guess is not something too common.

**Comment by KarelPeeters** [comment]
Ah and I hit it twice with the exact same condition as well, that's unlucky. Makes sense though!

**Pull request merged**
