### PR TITLE
Remove Cargo.lock and add to .gitignore

### PR DESCRIPTION
**Pull request by Xaeroxe**
Cargo.lock being checked into the repository hides problems that can occur when this is used in the field, because when used as a build-dependency the Cargo.lock file is not respected.

Case in point: https://github.com/alexcrichton/proc-macro2/issues/221

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Note: I expect this to fail CI because proc-macro2 1.0.11 seems to contain a semver breakage. See https://github.com/alexcrichton/proc-macro2/issues/221

**Comment by Xaeroxe** [comment]
proc-macro2 1.0.12 was just released, meaning this should now pass, so I force pushed to retry CI.

**Comment by emilio** [comment]
I don't understand this patch: Sure, `Cargo.lock` is useless when bindgen is used as a dependency, but not when it's used as a binary, right?

**Comment by Xaeroxe** [comment]
Hmm ok, that's new to me. I wasn't aware bindgen had a use case as a binary. I'll do some research on that.

**Comment by Xaeroxe** [comment]
Okay, I see. Good enough reason to keep it.

**Pull request closed without merging**
