### PR TITLE
Allow static and dynamic linking

### LINKED ISSUE #1617: Allow statically linking libclang
The bindgen Cargo.toml mentions a "static" feature, but it doesn't seem to connect to anything. Its dependency on clang-sys always sets the "runtime" features, which forces runtime dynamic loading.

I'd like to build bindgen statically linked with libclang, mostly to make deployment easier. It would be nice to be able to pass the "static" feature through to clang-sys rather than always requiring "runtime".

### PR DESCRIPTION
**Pull request by jsgf**
Currently bindgen always uses clang-sys with the "runtime" feature -
that is, load libclang at runtime with dlopen (or similar)
at runtime.  This PR keeps this default, but also
- adds "static" to statically link libclang
- without either "runtime" or "static", link with the shared library

Many distributions don't ship with a static libclang, but linking with the dynamic
library will use normal ld.so mechanisms to define where the .so file should be found.
(Ditto for the Mac and Windows equivalents.)

Fixes #1617

### CODE REVIEW

**Comment by jsgf** [comment]
> Huh, I thought ::is_loaded() and co would not work on statically-linked stuff.

It doesn't - they're all behind `#[cfg(feature = "runtime")]`.

**Comment by emilio** [comment]
Then how does this build?

**Comment by jsgf** [comment]
> Then how does this build?

? I added the necessary `#[cfg(...)]` conditional builds to `lib.rs`.

**Comment by emilio** [comment]
Sorry, we were talking past each other looks like :)

I was talking about the individual function's `is_loaded()` checks, like `clang_Foo::is_loaded()` that we have sprinkled around in the codebase.

But looks like clang-sys stubs them properly: https://github.com/KyleMayes/clang-sys/blob/ad5b1d0c64b19c4bfe00df6dfd661b80203dd161/src/link.rs#L195

**Comment by jsgf** [comment]
@emilio The checks are failing because this doesn't support libclang <= 4.0 any more - it tries to resolve symbols which don't exist in those versions. It might work with "runtime" because it only dynamically looks up symbols which do exist.

**Comment by emilio** [comment]
> @emilio The checks are failing because this doesn't support libclang <= 4.0 any more - it tries to resolve symbols which don't exist in those versions. It might work with "runtime" because it only dynamically looks up symbols which do exist.

Yeah, that's ~expected, I guess... Can we not test building the static version in those rather than removing the platforms? What's what triggers the `static` feature?

Alternatively, we need to remove a bunch of `tests/expectations/libclang-3.*` and same for `4`... I can do that as a followup but I'd like to keep at least 4.0 if we can (clang 3 is pretty old anyway at this point).

**Comment by jsgf** [comment]
It's triggered by non-"runtime". (nothing) is link with whatever is available (static or dynamic), and "static" is specifically statically link. "static" is hard to test because libclang doesn't build static out of the box and I haven't found any prebuilt libclangs available as static. But clang-sys does support static, so presumably someone is using it (well, including me, but we're using a slightly different mechanism).

Are you suggesting:
1. delete the 3.x tests
2. make the 4.x tests conditional on "runtime"
?

**Comment by emilio** [comment]
(FWIW, I haven't forgotten about this and still looks good. Will try to figure out a way to test this properly without regressing the `dynamic` clang support while I address similar CI issues due to the clang 9.0 release, probably over the weekend or on friday)

Thanks again for this!

**Comment by emilio** [comment]
(And really sorry for the lag replying, I had missed your previous comment)

**Comment by jsgf** [comment]
Do you need me to rebase it?

**Comment by emilio** [comment]
That'd be ideal, but no worries if you don't get to it.

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/pull/1646 is the version that adds support for libclang 9 on CI. That should allow to test this, and we should be able to avoid testing on other platforms.

**Comment by jsgf** [comment]
Rebased; fixed trivial conflict

**Comment by emilio** [comment]
So I put in https://github.com/rust-lang/rust-bindgen/pull/1649 my current WIP.

One annoyance of having two separate features is that downstream crates that want to use `no-default-features` can't get the advantages of the `runtime` feature, or otherwise they need to specify it, which means that other crates can't specify `static`.

I think ideally we'd make `runtime` built into clang-sys, but not sure how easy to do that is...

**Comment by jsgf** [comment]
I think that's a fundamental problem with using features this way - it isn't intended to support non-cumulative build-time options, and trying to do so breaks things. On the other hand, there's no better suited alternative mechanism.

**Comment by emilio** [comment]
So I gave a shot at finishing this, but apparently there are no pre-built static libclang versions, so we'd need to build our own which is not great...

Is the plan to build your own libclang.a and distribute it statically linked? Anyhow I guess I can land the patch without the tests if you need it and got it working.

**Comment by jsgf** [comment]
Yes, the clang build system seems to make generating a static libclang really tricky, and I couldn't find any Linux distro which ships a prebuilt static libclang. However our internal libclang has a static build, so its useful for that.

The non-`static`, non-`runtime` bindgen build will link to the shared libclang at build time which is logically identical to static linking from a code perspective - it just has the deployment question of whether the libclang is available at runtime at a path where it can be found.

So I'm not too concerned about not specifically testing `static` so long as non-`runtime` also works. This isn't ideal but 🤷‍♂.

**Comment by emilio** [comment]
Ok, so I landed #1649 with your changes and a slightly different/smaller set of CI tweaks, so that this is tested to the extent possible based on the comment above.

Thanks for the patch!

**Comment by lopopolo** [comment]
Hi @emilio this fix added a new default feature which wasn't mentioned in the changelog. This made upgrading my dependency with `default-features = false` tricky because I couldn't track down the errors from `clang-sys`.

Can we add a note to the changelog when features are added?

**Comment by emilio** [comment]
Yeah, that's fair, I added a changelog note just now, but I'll keep it in mind for the future too. Thanks :)

**Pull request closed without merging**
