### PR TITLE
Safe classes

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
Note: this PR is very much work in progress. You (bindgen authors) can take a look at it to get my idea and comment if you like the idea and check if the way I'm doing it is correct, but it is not ready to be merged (among other things some unit tests are failing). 
So please comment if you think my idea is good or if you think I'm just wasting my time, but don't comment (yet) whether small things (like indentation) are correct. 

Hello,

this PR, enables us to write e.g.
```
let mut var = Box_MyClass::new();
var.memberfunction();
```

This would allocate memory on the heap, construct a MyClass object there and safes a pointer to it in var. You can then call memberfunctions and at the end first the MyClass destructor will be called, then the memory will be freed.

The old way of putting objects on the stack is problematic, because Rust will memmove them, which breaks some Classes. (Note that I did not remove the old way.)

I still need to write getters and setters for accessing member functions and I need to document everything in the user Guide, but this will follow shortly.

The code generated by the example looks like this:

```
struct Box_MyClass {
    ptr: *mut u8,
}
impl Box_MyClass {
    #[inline]
    pub fn memberfunc(&mut self) {
        unsafe { MyClass_memberfunc(self.ptr as *mut MyClass) }
    }
    #[inline]
    pub fn new() -> Self {
        unsafe {
            let ret = Self {
                ptr: ::std::alloc::alloc(
                    ::std::alloc::Layout::from_size_align(20usize, 4usize)
                        .unwrap(),
                ),
            };
            MyClass_MyClass(ret.ptr as *mut MyClass);
            ret
        }
    }
}
impl Drop for Box_MyClass {
    fn drop(&mut self) {
        unsafe {
            MyClass_MyClass_destructor(self.ptr as *mut MyClass);
            ::std::alloc::dealloc(
                self.ptr,
                ::std::alloc::Layout::from_size_align(20usize, 4usize).unwrap(),
            );
        }
    }
}
```

### CODE REVIEW

**Comment by simlay** [comment]
I'm by no means any source of authority on this topic (and haven't fully read your PR) but I've spent a lot of time this year working on the objective-c support for bindgen. From my experience, having an alloc function is safe and it's what the [objective-c generated bindings](https://github.com/rust-lang/rust-bindgen/blob/ba4312f7457ec196a8291b4fdc70f2d174ccfe17/tests/expectations/tests/objc_class.rs#L27) do.

I would be weary about implementing the the free stuff as an `impl Drop`. I spent a lot of time trying to take advantage of the objective-c, [Manual Retain-Release](https://www.tutorialspoint.com/objective_c/objective_c_memory_management.htm) features with the hope that a `impl Clone` would increment the retain counter, and `impl Drop` would do the release (decrement the counter) however, certain calls in the objective-c would increase this counter (if you pass a UIView to a parent UIView, it'll increment in twice and then decrement it). The thing on the other side of the FFI is unsafe and can maybe use that object you've already freed because it's gone out of scope in rust land. Anyway, that's my cents.

**Comment by Volker-Weissmann** [comment]
> 
> I would be weary about implementing the the free stuff as an `impl Drop`. I spent a lot of time trying to take advantage of the objective-c, [Manual Retain-Release](https://www.tutorialspoint.com/objective_c/objective_c_memory_management.htm) features with the hope that a `impl Clone` would increment the retain counter, and `impl Drop` would do the release (decrement the counter) however, certain calls in the objective-c would increase this counter (if you pass a UIView to a parent UIView, it'll increment in twice and then decrement it). The thing on the other side of the FFI is unsafe and can maybe use that object you've already freed because it's gone out of scope in rust land. Anyway, that's my cents.

My idea is that at the end of this PR, you can take a C++ library, read the tutorial/documentation and write rust code that looks a lot like the C++ code in the tutorial/documentation.. So my goal is not directly to be safe, it is to be identical to the equivalent C++ code. Consider this rust code:
```rust
{
    let mut var = Box_MyClass::new();
    var.memberfunction();
} 
function();
```
If the C++ code of memberfunction() puts the *this pointer in a global variable and function() reads this pointer, the code above will be UB. But I think this is acceptable, because the equivalent C++ code:
```cpp
{
    MyClass var;
    var.memberfunction();
} 
function();
```
 would also be UB. As I said, my goal is that rust code does (ideally) exactly the same as the equivalent C++ code. And in C++ code, the memory is freed once the variable is dropped.

Of course it is bad that this enables you to accidentally write UB if you are not careful. But this is the price you have to pay if you use a C++ library, whether you call it from C++ or from Rust.

**Comment by Volker-Weissmann** [comment]
> umbrella The latest upstream changes (presumably [db3d170](https://github.com/rust-lang/rust-bindgen/commit/db3d170d3bb5339336e0cfc96a1653ad25793507)) made this pull request unmergeable. Please resolve the merge conflicts.

I know. This is still a draft and will probable take a month or so to be merge ready.

**Comment by kulp** [comment]
> My idea is that at the end of this PR, you can take a C++ library, read the tutorial/documentation and write rust code that looks a lot like the C++ code in the tutorial/documentation.

@Volker-Weissmann, I have not personally used https://github.com/dtolnay/cxx, but what you describe sounds like what I understand the `cxx` crate to do (notably, generating safe bindings between C++ and Rust).

Do I misunderstand?

**Comment by Volker-Weissmann** [comment]
No, you are right. I abandoned this PR, once I found https://github.com/google/autocxx

**Pull request closed without merging**
