### PR TITLE
ci: always try to find a nightly toolchain with rustfmt.

### PR DESCRIPTION
**Pull request by emilio**

### CODE REVIEW

**Comment by kulp** [comment]
Is this PR concerned with avoiding CI failures due only to `rustfmt` not being available in nightly, as is the case again on 2020-06-13, [since 2020-06-11](https://rust-lang.github.io/rustup-components-history/) ?

If so, what remains to be done, if known ? Perhaps I could finish the needed work.

**Comment by emilio** [comment]
Yes, that's the idea, rustfmt seems to get broken very easily nowadays. I need to dig into what the failure is and fix it, not sure what the next steps are without that :)

**Comment by kulp** [comment]
A few months ago I had seen a shell incantation that would look up the last `nightly` with `rustfmt` in it and install that one. Since the only current use for the nightly in `bindgen`'s CI is for `rustfmt` (I think), I will try to find (or construct) that incantation in case it is helpful.

**Comment by emilio** [comment]
Ah, it seems this is green modulo an error that's fixed in master already. So the incantation I ended up with should hopefully be good enough. Though simplifications welcome!

**Comment by kulp** [comment]
I think I recognize the incantation you are using, and it is better than the one I was writing (which used `curl` and `jq`). Thanks !

**Comment by emilio** [comment]
PR branch is green.

**Comment by emilio** [comment]
Thank you for nagging @kulp!

**Pull request merged**
