### PR TITLE
Add `--cxx` flag

### PR DESCRIPTION
**Pull request by pvdrz**
Addresses #1456

### CODE REVIEW

**Review by kulp — APPROVED** [review]
👍

**Review by emilio — COMMENTED** [review]
Not particularly opposed to this, but how does this address https://github.com/rust-lang/rust-bindgen/issues/1456?

In that issue, the user was using the `Builder` API to use `c++` directly. I think to address that we should probably either adjust the docs to provide an example that passes the two arguments separately, or maybe just add an `add_cxx_flags` API there that effectively does `clang_args(["-x", "c++"])`. But honestly I think the example would be more than enough.

**Comment by pvdrz** [comment]
I'd say that if someone asks for c++ support and the answer is
> just add the `cxx` arg

There is less chance for error than with
> just add the `-x c++` clang arg

regardless of what documentation says. 

I don't have super strong opinions about this feature so I'm OK with not merging this.

**Comment by kulp** [comment]
See also #1852 and #1855; "-x c++" seems to be a papercut for more than one person.

I do think this PR might "address" (in the sense of mitigating) #1456, but not close it. I had assumed that was why @pvdrz used the term "address" anyway.

**Comment by emilio** [comment]
> I'd say that if someone asks for c++ support and the answer is
> 
> > just add the `cxx` arg
> 
> There is less chance for error than with
> 
> > just add the `-x c++` clang arg
> 
> regardless of what documentation says.

Not really, `--cxx` is not a clang-arg (it's a bindgen arg), so if you use `clang_args(["--cxx"])` it'll error, right? Or am I missing something?

**Comment by emilio** [comment]
Right, but the original issue was about the library usage, so this patch doesn't change anything there afaict.

**Comment by pvdrz** [comment]
this also includes a `.cxx()` method @emilio

**Pull request closed without merging**
