### PR TITLE
Add thiscall_abi to stable version Rust 1.73.

### PR DESCRIPTION
**Pull request by rodrigorc**
1.73 Changelog:
- https://github.com/rust-lang/rust/releases/tag/1.73.0

Stabilization issue:
- https://github.com/rust-lang/rust/pull/114562/

----
 Maybe there are some tests to be fixed. I'm not quite sure how to review those.

### CODE REVIEW

**Comment by pvdrz** [comment]
It would be good if you could add a test like https://github.com/rust-lang/rust-bindgen/blob/main/bindgen-tests/tests/headers/win32-thiscall_nightly.hpp and https://github.com/rust-lang/rust-bindgen/blob/main/bindgen-tests/tests/headers/win32-thiscall_1_0.hpp using `--rust-target=1.73`.

**Comment by rodrigorc** [comment]
Added a test case, copied from the nightly but with stable 1.73 instead.

BTW, a bit off-topic, the `test-one.sh` script does not apply the `--target` option chosen from the header file. That took me some time to notice...

**Comment by rodrigorc** [comment]
It looks like there was some test that failed. I think that is because they are not obeying the `--target` option, `thiscall` exists only in i686-pc-windows-* targets, I think.

The `win32-thiscall_nightly` test doesn't fail because the `.rs` file contains this line:
```
#![cfg(feature = "nightly")]
```
So if you use a non-nightly compiler, it will just skip the whole file and trivially succeed!

I guess I could do a similar thing in my new `.rs` file: `#![cfg(target = "i686-pc-windows-msvc")]` or something, but it looks a bit like cheating.

**Comment by rodrigorc** [comment]
Hi @pvdrz ! Any feedback about this PR?

**Comment by tgross35** [comment]
@rodrigorc can you fix the macos CI test?

**Comment by rodrigorc** [comment]
> @rodrigorc can you fix the macos CI test?

I just force-pushed a fix for that. I'm not totally sure if that is the proper solution, but I run it changing some things here and there and it looked mostly ok, but I don't have a macos, so I can't be sure about that part.

**Pull request merged**
