### PR TITLE
Add a member names callback for ParseCallbacks

### PR DESCRIPTION
**Pull request by pavlukivan**
I'm new to both rust and bindgen, so please tell me if there's something I'm doing wrong here, but at least it works

### CODE REVIEW

**Comment by pavlukivan** [comment]
just found a bug in test generation, don't merge yet

**Comment by pavlukivan** [comment]
hopefully should be good now

**Comment by pavlukivan** [comment]
Use case is similar to the `item_name` callback. I personally used it to snake case'ify every member function in the bindings. As of tests - there aren't any tests for ParseCallbacks in the first place, and I can't run the test suite as I'm using Windows.

**Comment by emilio** [comment]
There definitely are tests for parse callbacks: https://github.com/rust-lang/rust-bindgen/blob/de23676c4b7feca98c8418bf701ce5ce80f7e4e7/bindgen-integration/build.rs#L17

**Comment by kulp** [comment]
@pavlukivan, maybe my concurrent work in #1793 will be helpful to you ? I added some tests there (although I do not know if I did it well, since my code is still pending review).

**Comment by pavlukivan** [comment]
I see, I couldn't find the test because it wasn't using `expectations`. I'll see what I can do.

**Comment by pavlukivan** [comment]
i don't need this anymore so I will close this and let others do it if the need arises

**Pull request closed without merging**
