### PR TITLE
Improve the UB situation in layout tests.

### PR DESCRIPTION
**Pull request by emilio**
This is #2055 with some extra fixes

### CODE REVIEW

**Comment by jyn514** [comment]
Hi @emilio, is there anything blocking you from merging this? It would be super helpful for all the projects using bindgen :)

**Comment by emilio** [comment]
Yeah, some tests are failing, I don't recall the specifics, need to look into that, will re-push.

**Comment by elichai** [comment]
Out of curiosity, why zero memory and not a `MaybeUninit`? 
This means that in the future you can't add support for things like str / refrences / boxes / NonNull etc. (anything that has a niche or validity rules)

(Using MaybeUninit like that is explicitly defined here: https://doc.rust-lang.org/beta/std/mem/union.MaybeUninit.html#initializing-a-struct-field-by-field)

**Comment by kulp** [comment]
It appears that this (like #2055) has a little more in it than #2033 did, but since #1651 is now closed, I am inferring that this PR is no longer needed, so I am closing it.

If I missed something, let me know.

**Pull request closed without merging**
