### PR TITLE
Add --no-default <regex> flag

### LINKED ISSUE #963: Allow specifying certain types we shouldn't derive/impl Default for
Add `--no-default <regex>` and `Builder::no_default(String)` to supply regexes for matching against types that we should not derive or implement `Default` for.

Adding this feature involves:

* [ ] Adding a new `RegexSet` member to `bindgen::Builder` (similar to the `whitelisted_types` set).

* [ ] A `Builder` method to add strings to that `RegexSet`.

* [ ] Plumbing in `src/options.rs` to convert `--no-default <regex>` CLI flags into invocations of the builder method.

* [ ] Making the `MonotoneFramework::constrain` function in `src/ir/analysis/derive_default.rs` check if the given item is explicitly marked not to be `Default`, and if so, inserting it into the `self.cannot_derive_default` set via `return self.insert(id)`.

* [ ] Tests!

    * [ ] When the no-default type is transitively referenced by a whitelisted item

    * [ ] When the no-default type is explicitly whitelisted

    * [ ] When the no-default type is marked opaque

### PR DESCRIPTION
**Pull request by GyrosOfWar**
Don't merge yet! Implementation of the feature, still missing tests. Fixes #963

### CODE REVIEW

**Comment by fitzgen** [comment]
Let me know when I should take a look :)

**Comment by fitzgen** [comment]
Hi @GyrosOfWar, still planning on adding some tests here? Any questions I can answer?

**Comment by GyrosOfWar** [comment]
Yes, I'll do that in the next couple of days.

**Comment by pepyakin** [comment]
@GyrosOfWar thanks for the status update!

**Comment by fitzgen** [comment]
@GyrosOfWar still planning on adding those tests? ;)

**Comment by Lokathor** [comment]
bump?

**Comment by emilio** [comment]
Closing for inactivity. This also needs a pretty big rebase, though it seems like a fine feature, so happy to take a look if somebody takes over this work.

**Pull request closed without merging**
