### PR TITLE
Add additional helpers to bitfield data structure

### LINKED ISSUE #2674: bitfields raw pointer accessors
When creating bindings for a struct with bitfields the accessor functions that are created take an immutable receiver (`&self`). This is a problem if the underlying type is used by both Rust and C, since Rust is not allowed to create `&self` references, since the C side might modify the value at any time.
One solution could be to create raw accessor functions that allow access via `*const Self`.

### Input C Header

```C
struct foo {
    unsigned available:1;
};
```

### Bindgen Invocation

```
$ bindgen input.h
```

```rust
impl foo {
    #[inline]
    pub fn available(&self) -> ::std::os::raw::c_uint {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set_available(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        available: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let available: u32 = unsafe { ::std::mem::transmute(available) };
            available as u64
        });
        __bindgen_bitfield_unit
    }
}
```

### Expected Results

Additional functions that should be generated:

```rust
impl foo {
    #[inline]
    pub unsafe fn raw_available(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(__BindgenBitfieldUnit::raw_get(
                addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u32)
        }
    }

    #[inline]
    pub unsafe fn raw_set_available(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            __BindgenBitfieldUnit::raw_set(addr_of!((*this)._bitfield_1), 0usize, 1u8, val as u64)
        }
    }
}
```

This also requires changes to the generated `__BingenBitfieldUnit`.

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2674

### CODE REVIEW

**Comment by jbaublitz** [comment]
@y86-dev Can you confirm that this resolves your issue? Now that it's passing CI, I think it's ready for review.

@ojeda @emilio Also feel free to let me know if you have any feedback.

**Comment by y86-dev** [comment]
Hi, thanks for working on this!
I tried your branch and the code seems to look like what we would want, but I have a couple notes:
1. in the kernel, we don't have `std` (and I would imagine that many users of `bindgen` would not want to rely on having it, do you test for this in your CI?) and thus the generated code doesn't compile. The fix is probably to just replace `std` with `core`.
2. I am not so sure if my initial naming suggestion was the best, at the moment I like `field_raw` better than `raw_field` for the raw getter, the setter name seems fine to me, but if you think making it `set_field_raw`, then that also seems good to me.

Otherwise the code looks good to me, maybe Miguel finds something else. Also cc @nbdd0121, it might be a good idea to let him also take a look.

**Comment by jbaublitz** [comment]
> Hi, thanks for working on this! I tried your branch with the kernel repo and the code seems to look like what we would want, but I have a couple notes:
> 
>     1. in the kernel, we don't have `std` (and I would imagine that many users of `bindgen` would not want to rely on having it, do you test for this in your CI?) and thus the generated code doesn't compile. The fix is probably to just replace `std` with `core`.

Whoops, I saw that bindgen used `std` in generated code, but it must be feature flagged. Regardless, I can see how that would be undesirable. I'll fix that up.

> 
>     2. I am not so sure if my initial naming suggestion was the best, at the moment I like `field_raw` better than `raw_field` for the raw getter, the setter name seems fine to me, but if you think making it `set_field_raw`, then that also seems good to me.

Okay I'll change it!

> 
> 
> Otherwise the code looks good to me, maybe Miguel finds something else. Also cc @nbdd0121, it might be a good idea to let him also take a look.

**Comment by y86-dev** [comment]
I tested it again and it LGTM, thanks!

**Comment by jbaublitz** [comment]
@pvdrz Hi! This PR is ready I think assuming @ojeda is okay with it.

**Review by pvdrz — APPROVED** [review]

**Pull request merged**
