### PR TITLE
ci: Try to fix macOS runner

### PR DESCRIPTION
**Pull request by emilio**
Now seems to run on arm64 out of the blue...

### CODE REVIEW

**Comment by pvdrz** [comment]
It seems we're both trying to fix it: https://github.com/rust-lang/rust-bindgen/pull/2820 :rofl: 

i believe this happens because llvm was built with a different xcode version or something. However, I think we're just being affected by this: https://github.com/actions/runner/issues/3256

**Comment by emilio** [comment]
> I think there's not much we can do regarding LLVM 9 on macos to be honest, specially if apple decides to drop x86 support eventually

Yeah, that's why I approached this by trying to test in a new-ish llvm version... I think part of the issue is that somehow quote and co are using `cc` as a linker, rather than the LLVM we just downloaded...

**Comment by emilio** [comment]
But even with that fixed it fails so nvm...

**Comment by leighmcculloch** [comment]
> Now seems to run on arm64 out of the blue...

According to this post by GitHub in January the `macos-14` runner is exclusively arm64:
- https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

This definitely landed in a way that was surprising though.

**Comment by emilio** [comment]
@pvdrz apparently macos-latest was macos-12, not macos-13, so downgrading to that fixes CI.

**Pull request merged**
