### PR TITLE
Fix const array issue

### LINKED ISSUE #2683: Constant array treated as mutable pointer
### Input C/C++ Header

```C++
typedef struct {
    int field;
} strct;

typedef strct typ[1];

void function(const typ a, const strct *b);
```

### Actual Results

```rust
pub type typ = [strct; 1usize];
extern "C" {
    pub fn function(a: *mut strct, b: *const strct);
}
```

### Expected Results
```rust
pub type typ = [strct; 1usize];
extern "C" {
    pub fn function(a: *const strct, b: *const strct);
}
```

### PR DESCRIPTION
**Pull request by rsammelson**
Fix #2683. Fairly hacky fix right now, but it doesn't seem to break any tests.

### CODE REVIEW

**Comment by tgross35** [comment]
@rsammelson can you explain the test changes? The diff shows these files changed

```diff
 .../tests/constified-enum-module-overflow.rs  | 15 ++++++++++++-
 .../tests/issue-544-stylo-creduce-2.rs        |  2 +-
 .../libclang-9/ptr32-has-different-size.rs    |  6 +++---
 .../expectations/tests/struct_typedef_ns.rs
```

But none of those seem to have anything to do with const/mut pointers

**Comment by rsammelson** [comment]
I'm not sure what caused that change, let me fix it.

**Comment by rsammelson** [comment]
@tgross35 It should be fixed now.

**Comment by tgross35** [comment]
Thanks. Could you add a test for the change you made?

**Comment by emilio** [comment]
The changes before are because of newer libclang versions. We should update CI and expectations to newer libclang IMO. But not in this patch of course.

**Comment by rsammelson** [comment]
@tgross35 I don't understand why the tests are failing.

**Comment by tgross35** [comment]
Yeah, the `unused_imports` don't seem like your fault. Maybe something in CI changed recently.

I'll test it out here https://github.com/rust-lang/rust-bindgen/pull/2763.

**Comment by tgross35** [comment]
Not sure where those errors appeared from but the changes in https://github.com/rust-lang/rust-bindgen/pull/2763 seem to fix them. @emilio might know more.

You don't have to do anything except rebase whenever that is mered.

**Comment by emilio** [comment]
> Not sure where those errors appeared from but the changes in #2763 seem to fix them. @emilio might know more.

Yeah, we use rust stable so whenever a rust update introduce warnings we hit this. Should be fixed now tho.

**Review by emilio — APPROVED** [review]
The fix looks reasonable. Please rebase and we can get this merged :)

**Comment by emilio** [comment]
(I tried to do it automatically, let's see)

**Pull request merged**
