### PR TITLE
Bump most dependencies without change to MSRV

### PR DESCRIPTION
**Pull request by nyurik**
Bumps all the dependencies with 

```
cargo +nightly -Z unstable-options update --breaking
cargo update
```

Due to MSRV change for the env_log, I kept it back

### CODE REVIEW

**Comment by pvdrz** [comment]
I don't think we should raise the msrv so hastily. Does any of these dependency bumps have any critical update or something?

**Comment by nyurik** [comment]
Not to my knowledge. 1.74 was released over a year ago on [16 November, 2023](https://releases.rs/docs/1.74.0/). What range of Rust versions should the latest  bindgen maintain?  Note that most people who may want an older compiler could simply stick to the older bindgen until they need new functionality - by which time even more time would pass after 1.74.

In the mean time, I could of course update just some of the non-msrv-affecting dependencies

**Comment by ojeda** [comment]
One possible policy is picking something that major distributions are carrying.

For instance, current Debian Stable (bookworm) has 1.63.0 and trixie ideally will get 1.85.0 (i.e. the very latest by the time it releases). Currently they are at 1.82.0 already (i.e. the very latest at the time of writing).

Perhaps following them between releases is too slow for `bindgen`, but nevertheless whatever Debian picks is usually good to take into account, at least for a while.

**Comment by nyurik** [comment]
I did a few trials - updating just the non-msrv affecting dependencies here

**Comment by pvdrz** [comment]
> What range of Rust versions should the latest bindgen maintain? 

This is an excellent question. To be honest, we don't have enough visibility to know which versions of Rust are used to compile bindgen.

> Note that most people who may want an older compiler could simply stick to the older bindgen until they need new functionality - by which time even more time would pass after 1.74.

Yes, however there have been instances in the past where people require a specific bugfix for an older version of bindgen just because the fix was added on a newer version with a higher msrv. Keeping a lower msrv makes this less likely.

> One possible policy is picking something that major distributions are carrying.
> 
> For instance, current Debian Stable (bookworm) has 1.63.0 and trixie ideally will get 1.85.0 (i.e. the very latest by the time it releases). Currently they are at 1.82.0 already (i.e. the very latest at the time of writing).

Yes, I think this is a sensible option specially since debian is widely used as the reference point for a reasonable msrv. (@emilio what do you think? would it be reasonable to set this policy of matching the latest debian stable rust version with our msrv?)

**Pull request merged**
