### PR TITLE
Look at correct cursor when checking field mutability.

### PR DESCRIPTION
**Pull request by SilensAngelusNex**
`cursor` here points at the type's declaration, while `cur` points at the field declaration currently being visited. This meant `is_mutable` was always being set to `false`.

AFAICT, the information about whether fields are declared `mutable` isn't actually used anywhere yet, so no changes to the tests.

r? @emilio

### CODE REVIEW

**Review by emilio — COMMENTED** [review]
So this was introduced in 0ea208b7e6ef54fa1f40efb7912d7040cf2e4fa9, but it seems we got rid of that at some point. I'd prefer to remove all the `is_mutable` code instead of this.

**Comment by SilensAngelusNex** [comment]
It looks like wrapping mutable fields with `*Cell` was removed in `cfdf15f`; is that intentional? Personally, I'd expect mutable fields to be wrapped in cells or marked in some other way.

If you don't think bindgen should be treating `mutable` and non-`mutable` members differently, I can remove all the `is_mutable` code.

**Comment by emilio** [comment]
I don't think anybody has missed this feature so far. Wrapping it in `Cell` only works for Copy types, we should be using `UnsafeCell` for that.

But I think we should remove the dead code for now. If somebody wants to implement `UnsafeCell`-wrapping then it's easy to rescue this code from history and add tests.

**Review by emilio — APPROVED** [review]
Thanks!

**Pull request merged**
