### PR TITLE
Don't redefine structs that have been forward declared

### LINKED ISSUE #1864: Duplicate definitions with forward declared pointer types
### Input C/C++ Header

```C++
CAPI void alt_RotationLayout_CAPI_Free_Forward(struct alt_RotationLayout* ptr);
typedef struct alt_RotationLayout {
    float roll;
    float pitch;
    float yaw;
} alt_RotationLayout;
CAPI void alt_RotationLayout_CAPI_Free(struct alt_RotationLayout* ptr);
```

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()
        .rustfmt_bindings(true)
        .layout_tests(false)
        .header(format!("./altv-capi-{}-static-{}/include/altv-capi-{}.h", kind, platform, kind))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        .generate()
        .expect("Unable to generate bindings");

    bindings
        .write_to_file(format!("src/altv_{}.rs", kind))
        .expect("Couldn't write bindings!");
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.54.1 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub type nullptr_t = *mut ::std::os::raw::c_void;
extern "C" {
  pub fn alt_RotationLayout_CAPI_Free_Forward(ptr: *mut alt_RotationLayout);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alt_RotationLayout {
  pub roll: f32,
  pub pitch: f32,
  pub yaw: f32,
}
extern "C" {
  pub fn alt_RotationLayout_CAPI_Free(ptr: *mut alt_RotationLayout);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alt_RotationLayout {
  pub _address: u8,
}
```

### Expected Results

No duplicate definitions (when using forward declared pointers).

```rust
/* automatically generated by rust-bindgen 0.54.1 */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub type nullptr_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alt_RotationLayout {
  pub roll: f32,
  pub pitch: f32,
  pub yaw: f32,
}
extern "C" {
  pub fn alt_RotationLayout_CAPI_Free(ptr: *mut alt_RotationLayout);
}
```

### PR DESCRIPTION
**Pull request by 7Hazard**
Don't redefine structs that have been forward declared. This will keep track of all struct symbols to know whether a struct has already been defined, similarly to how functions are tracked (seen_function, saw_function).
Resolves #1864

### CODE REVIEW

**Comment by 7Hazard** [comment]
I was also hesitant in this approach. I realized the codegen reaches this part when it shouldn't https://github.com/rust-lang/rust-bindgen/blob/master/src/codegen/mod.rs#L1823.

I was able to reproduce the error locally with the example you provided.  
Clearly this seems to be done as a post-process measure but doesn't take into consideration that the struct was defined in the meantime of the codegen. Im not familiar with the codebase but I will try to find what triggers this.

**Comment by emilio** [comment]
> I was able to reproduce the error locally with the example you provided.

Oh, that's interesting. Which libclang version you have installed?

**Comment by 7Hazard** [comment]
```
clang version 11.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

Using the windows installer provided in LLVM's page.

**Comment by 7Hazard** [comment]
So I can't find why exactly what triggers the forward declarations and how to prevent them from triggering if the forward declaration was defined later on by the header, but I thought I'd share the solution im currently using in my fork.

**Pull request closed without merging**
