### PR TITLE
Bump hashbrown to 0.2

### PR DESCRIPTION
**Pull request by eclipseo**
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>

### CODE REVIEW

**Comment by emilio** [comment]
Looks good but needs a lockfile update. I think I'll actually remove the hashbrown dependency now that it's going to be in std, since the perf benefit wasn't _that_ big, and you save building a bunch of dependencies.

**Comment by ignatenkobrain** [comment]
@emilio any news here?

**Comment by emilio** [comment]
Sorry, totally lost track of this. https://github.com/rust-lang/rust-bindgen/commit/b7e5d8d4d511066d0363ef72dbee2c66615b8dd4 should fix this. Let me know if you want a release or what not.

**Comment by ignatenkobrain** [comment]
@emilio release would be appreciated :)

**Pull request closed without merging**
