### PR TITLE
Clippy placation

### PR DESCRIPTION
**Pull request by amanjeev**

### CODE REVIEW

**Comment by amanjeev** [comment]
is this not needed or should not be done?

**Comment by pvdrz** [comment]
I'm not sure. Does this run with our msrv?

**Comment by amanjeev** [comment]
yea apart from the issues with bindgen and bindgen-cli using different msrv, this builds with msrv 1.60 for bindgen (not cli)

**Comment by amanjeev** [comment]
gitmergeblackhole

no approval, only merge

**Review by pvdrz — COMMENTED** [review]
approved :trollface:

**Pull request merged**
