### PR TITLE
ir: Fix wrong condition in bitfield alignment.

### LINKED ISSUE #1314: Bindgen fail to generate bindings for struct.
Header:
#include <stdint.h>                                                                                             
typedef struct {                                                                                                
  uint32_t f : 20;                                                                                              
  uint8_t f1 : 4;                                                                                               
  uint8_t f2 : 1;                                                                                               
  uint8_t f3 : 1;                                                                                               
  uint8_t f4 : 1;                                                                                               
  uint8_t f5 : 5;                                                                                               
  uint16_t f6;                                                                                                  
  uint8_t f7;                                                                                                   
  uint8_t f8;                                                                                                   
  uint8_t f9;                                                                                                   
  uint8_t f10;                                                                                                  
  uint8_t f11 : 2;                                                                                              
  uint8_t f12 : 4;                                                                                              
  uint16_t f13 : 10;                                                                                            
  uint8_t f14;                                                                                                  
  uint32_t f15 : 19;                                                                                            
} S; 

Bindgen command:
bindgen types.h -o t.rs
ERROR 2018-05-17T23:24:11Z: bindgen::codegen::struct_layout: Calculated wrong layout for S, too more 1 bytes

Bindgen version:
bindgen 0.36.1

### PR DESCRIPTION
**Pull request by emilio**
We should also align the allocation unit even if it's the first bitfield in the
allocation unit.

Fixes #1314

### CODE REVIEW

**Comment by emilio** [comment]
This is not quite right (fixes the layout, but we still look at the wrong offset)...

**Comment by emilio** [comment]
Oh, we look at the wrong offset in the _other_ test-case...

**Comment by fitzgen** [comment]
Is this ready for review? It isn't clear to me and CI is failing.

**Comment by emilio** [comment]
I need to decide which of the two cases I break, or move all our layout tracking to the time before we compute bitfields... :(

**Comment by emilio** [comment]
Closing for inactivity, fixing this properly is pretty hard too.

**Pull request closed without merging**
